<script type="text/javascript">

    if (typeof M2eProAmazonListingTutorial == 'undefined') {
        M2eProAmazonListingTutorial = {};
        M2eProAmazonListingTutorial.url = {};
        M2eProAmazonListingTutorial.formData = {};
        M2eProAmazonListingTutorial.text = {};
    }

    M2eProAmazonListingTutorial.text.confim_offer_show_video = '';
    M2eProAmazonListingTutorial.text.confim_close_video = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Are you sure?')); ?>';

    AmazonListingVideoTutorialHandlerObj = new VideoTutorialHandler(M2eProAmazonListingTutorial,'amazon_listing_video_tutorial_pop_up',
                                                                         '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('M2E Pro - Amazon/Magento Integration : Listings')); ?>',
                                                                         function(){});

    setTimeout(function() {
        ModuleNoticeObj.observeModulePrepareStart($('block_notice_amazon_listing_tutorial'));
    }, 50);

</script>

<div id="<?php echo $this->getContainerId() ?>">
    <div class="content-header">
    </div>
    <div>
        <div id="block_notice_amazon_listing_tutorial" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">

            <table>
                <tr>
                    <td>
                        <a href="javascript:" onclick="AmazonListingVideoTutorialHandlerObj.openPopUp()">
                            <img src="<?php echo $this->getSkinUrl('M2ePro/images/amazon-video-thumbnail.png'); ?>" alt="">
                        </a>
                        <h4 style="text-align: center">Amazom Listings (10 min. video)</h4>
                    </td>

                    <td style="padding: 10px  0 0 30px">
                        <?php
                            $listingTemplatesUrl = $this->getUrl('*/adminhtml_template_general/index');
                            $synchronizationTemplatesUrl = $this->getUrl('*/adminhtml_template_synchronization/index');
                            $sellingFormatTemplatesUrl = $this->getUrl('*/adminhtml_template_sellingFormat/index');

                            $listingsUrl = $this->getUrl('*/adminhtml_amazon_listing/add/step/1/clear/yes');

                            $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();

                            echo Mage::helper('M2ePro')->__(
                                'With M2E Pro you also have the option to set up templates. You can use the same template for similar products you want to list on Amazon.
                                <br>
                                With the help of these templates you don’t have to enter the same information over and over again for each product you want to list on Amazon.

                                <br>
                                There are two different templates. One of them is necessary to list on Amazon  and another one is necessary to control how the information between Amazon and Magento is synchronized.
                                <br>
                                <br>
                                Templates you’ll need in order to list on Amazon:
                                <ul style="margin-left: 15px; list-style: disc">
                                    <li><a href="%s">Selling Format Template</a>: In what format do you want to sell on Amazon? </li>
                                    <li><a href="%s">Synchronization Template</a>:  This template controls how the information between Amazon and Magento is synchronized and in which cases Amazon listings are revised, relisted or stopped.  This template is not bound to a product group with a specific attribute set, so it’s likely that you’ll only need one template to begin with. </li>
                                </ul>
                                <br>
                                <b>Note:</b> Only simple products is supported in current version. The support for variation items will be added in the future versions.<br><br>',
                                $sellingFormatTemplatesUrl, $synchronizationTemplatesUrl
                            );

                            echo $this->getChildHtml('confirm_tutorial');
                        ?>
                    </td>
                </tr>
            </table>

        </div>
    </div>
</div>

<div id="amazon_listing_video_tutorial_pop_up" style="display: none;">
    <div class="player_container" style="margin: 20px 5px; ">
       <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/odyMO2KABcs?version=3&amp;hl=ru_RU&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/odyMO2KABcs?version=3&amp;hl=ru_RU&amp;rel=0" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
    </div>
</div>