<div id="block_notice_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This page contains all created Listings. Use Templates filters to sort Listings by templates that they use in their settings.<br/>
    You can do different Actions either with a single Listing or a group of Listings.<br/>
    Actions for a single Listing you can find in the Action column of the grid. Choose a necessary option in the appropriate Listing dropdown to execute it.<br/>
    Mass actions are in the Actions dropdown at the top right corner of the grid. Select check-boxes of appropriate items,
    choose an Action from the dropdown and press the <span style="text-decoration: underline;">Submit</span> button.'); ?>
</div>