<script type="text/javascript">

    if (typeof M2eProBuyListingTutorial == 'undefined') {
        M2eProBuyListingTutorial = {};
        M2eProBuyListingTutorial.url = {};
        M2eProBuyListingTutorial.formData = {};
        M2eProBuyListingTutorial.text = {};
    }

    M2eProBuyListingTutorial.text.confim_offer_show_video = '';
    M2eProBuyListingTutorial.text.confim_close_video = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Are you sure?')); ?>';

    BuyListingVideoTutorialHandlerObj = new VideoTutorialHandler(M2eProBuyListingTutorial,'buy_listing_video_tutorial_pop_up',
                                                                         '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('M2E Pro - Rakuten.com/Magento Integration : Listings')); ?>',
                                                                         function(){});

    setTimeout(function() {
        ModuleNoticeObj.observeModulePrepareStart($('block_notice_buy_listing_tutorial'));
    }, 50);

</script>

<div id="<?php echo $this->getContainerId() ?>">
    <div class="content-header">
    </div>
    <div>
        <div id="block_notice_buy_listing_tutorial" class="block_notices_module" title="" subtitle="" collapseable="no" hideblock="no" always_show="yes">

            <table>
                <tr>
                    <td>
                        <a href="javascript:" onclick="BuyListingVideoTutorialHandlerObj.openPopUp()">
                            <img src="<?php echo $this->getSkinUrl('M2ePro/images/buy-video-thumbnail.png'); ?>" alt="">
                        </a>
                        <h4 style="text-align: center">Rakuten.com Listings (12 min. video)</h4>
                    </td>

                    <td style="padding: 10px  0 0 30px">
                        <?php
                            $listingTemplatesUrl = $this->getUrl('*/adminhtml_template_general/index');
                            $synchronizationTemplatesUrl = $this->getUrl('*/adminhtml_template_synchronization/index');
                            $sellingFormatTemplatesUrl = $this->getUrl('*/adminhtml_template_sellingFormat/index');

                            $listingsUrl = $this->getUrl('*/adminhtml_buy_listing/add/step/1/clear/yes');

                            $menuLabel = Mage::helper('M2ePro/Module')->getMenuRootNodeLabel();

                            echo Mage::helper('M2ePro')->__(
                            'With M2E Pro you also have the option to set up templates. You can use the same template for similar products you want to list on Rakuten.com.
                            <br>
                            With the help of these templates you don’t have to enter the same information over and over again for each product you want to list on Rakuten.com.
                            <br/><br/>
                            There are two different templates. One of them is necessary to list on Rakuten.com  and another one is necessary to control how the information between Rakuten.com and Magento is synchronized:
                            <br/><br/>
                            <ul style="margin-left: 15px; list-style: disc">
                                <li><a href="%s">Selling Format Template</a>: In what format do you want to sell on Rakuten.com? </li>
                                <li><a href="%s">Synchronization Template</a>:  This template controls how the information between Rakuten.com and Magento is synchronized and in which cases Rakuten.com listings are revised, relisted or stopped.  This template is not bound to a product group with a specific attribute set, so it’s likely that you’ll only need one template to begin with. </li>
                            </ul>
                            <br>',
                            $sellingFormatTemplatesUrl, $synchronizationTemplatesUrl);

                            echo $this->getChildHtml('confirm_tutorial');
                        ?>
                    </td>
                </tr>
            </table>

        </div>
    </div>
</div>

<div id="buy_listing_video_tutorial_pop_up" style="display: none;">
    <div class="player_container" style="margin: 20px 5px; ">
       <object width="853" height="480"><param name="movie" value="http://www.youtube.com/v/jUOcdYO9ZPM?version=3&amp;hl=ru_RU&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/jUOcdYO9ZPM?version=3&amp;hl=ru_RU&amp;rel=0" type="application/x-shockwave-flash" width="853" height="480" allowscriptaccess="always" allowfullscreen="true"></embed></object>
    </div>
</div>