<script type="text/javascript">

// transaction type
 var cco_type     = "sale";
 // transaction value
 var cco_value       = 0.00;
 // unique transaction identifier
 var cco_orderref = <?php echo Mage::getSingleton('checkout/session')->getLastOrderId() ?>
 // basket breakdown (CSV itemcode|quantity)
 var cco_basket = "itemcode1|price|quantity,itemcode2|price|quantity";

 // Added Comment
 
 // partner ID
 var cco_pid      = 5921;       
 var cco_url      = "http://track.social360.com/trnx.php?cco_pid=" + cco_pid + "&cco_type=" + escape(cco_type) + "&cco_value=" + escape(cco_value) + "&cco_orderref=" + escape(cco_orderref) + "&cco_basket=" + escape(cco_basket);
 document.write('<script type="text/javascript" src="' + cco_url + '"><\/script>');   

</script>