<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-container">
    <div class="header">
        <div class="currency-selector">
            <?php echo $this->getChildHtml('currency-selector') ?>
        </div>
        <div class="logo left">
            <?php if ($this->getIsHomePage()): ?>
                <h1><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else: ?>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif ?>
        </div>
        <div class="search left">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
		<div class="header-links right">
            <div class="right">
                <?php echo $this->getChildHtml('header-cart') ?>
            </div>	
            <div class="right">
                <?php echo $this->getChildHtml('header-links') ?>
            </div>	
        </div>
    </div>
</div>
