<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php
    if(Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ) {
        $homePage = true;
    } else {
        $homePage = false;
    }
	if(Mage::getSingleton('cms/page')->getIdentifier() == 'blog'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ) {
		$blog = true;
	} else {
		$blog = false;
	}
?>
<?php $_menu = $this->getHtml('level-top') ?>
<?php if($_menu): ?>
<div class="nav-container">
    <ul id="nav">
        <li class="level0 nav-1 level-top<?php if($homePage): ?> active<?php endif; ?>">
            <a class="level-top" href="<?php echo $this->getUrl() ?>">
                <span><?php echo $this->__('Home') ?></span>
            </a>    
        </li>
        <?php echo $_menu ?>
		<li class="level0 nav-1 level-top<?php if($blog): ?> active<?php endif; ?>">
            <a class="level-top" href="<?php echo $this->getUrl('blog') ?>">
                <span><?php echo $this->__('Blog') ?></span>
            </a>    
        </li>
    </ul>
</div>
<?php endif ?>
